export const SUBMIT_FEEDBACK = 'SUBMIT_FEEDBACK'
export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS'
export const SUBMIT_FEEDBACK_FAIL = 'SUBMIT_FEEDBACK_FAIL'
export const TOGGLE_FEEDBACK_CHANGE = 'TOGGLE_FEEDBACK_CHANGE'
