export const FETCH_SANDBOX_LIST = 'FETCH_SANDBOX_LIST'
export const FETCH_SANDBOX_LIST_SUCCESS = 'FETCH_SANDBOX_LIST_SUCCESS'
export const FETCH_SANDBOX_LIST_FAIL = 'FETCH_SANDBOX_LIST_FAIL'
export const FETCH_SANDBOX_LIST_CLEAR = 'FETCH_SANDBOX_LIST_CLEAR'

export const FETCH_LESSON_PAGINE = 'FETCH_LESSON_PAGINE'
export const FETCH_LESSON_PAGINE_SUCCESS = 'FETCH_LESSON_PAGINE_SUCCESS'
export const FETCH_LESSON_PAGINE_FAIL = 'FETCH_LESSON_PAGINE_FAIL'

export const FETCH_SECTION_PAGINE = 'FETCH_SECTION_PAGINE'
export const FETCH_SECTION_PAGINE_SUCCESS = 'FETCH_SECTION_PAGINE_SUCCESS'
export const FETCH_SECTION_PAGINE_FAIL = 'FETCH_SECTION_PAGINE_FAIL'

export const TOGGLE_DEBUG_PAGE_INIT = 'TOGGLE_DEBUG_PAGE_INIT'
export const FETCH_SECTION_DETAIL = 'FETCH_SECTION_DETAIL'
export const FETCH_SECTION_DETAIL_SUCCESS = 'FETCH_SECTION_DETAIL_SUCCESS'
export const FETCH_SECTION_DETAIL_FAIL = 'FETCH_SECTION_DETAIL_FAIL'

export const GALLERY_CHANGE_SELECT = 'GALLERY_CHANGE_SELECT'

// debug/run code
export const TOGGLE_RUNNING_CODE_CHANGE = 'TOGGLE_RUNNING_CODE_CHANGE'
export const DEBUG_RUNNING_CODE = 'DEBUG_RUNNING_CODE'
export const DEBUG_RUNNING_CODE_SUCCESS = 'DEBUG_RUNNING_CODE_SUCCESS'
export const DEBUG_RUNNING_CODE_FAIL = 'DEBUG_RUNNING_CODE_FAIL'
export const DEBUG_RUNNING_CODE_END = 'DEBUG_RUNNING_CODE_END'
export const DEBUG_RUNNING_CODE_CLEAR = 'DEBUG_RUNNING_CODE_CLEAR'
